version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cursonest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5499:5432"